export const LOAD_DATA_SUCSESS = 'LOAD_DATA_SUCSESS'
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE'
export const LOAD_CRYPTO_COURSE = `LOAD_CRYPTO_COURSE`
export const CRYPTO_CONVERTER_CHANGE = `CRYPTO_CONVERTER_CHANGE`
